---

- name: Install Python 3 and configure repositories
  hosts: all
  become: true
  tasks:
    - name: Install Python 3
      apt:
        name: python3
        state: present
      when: ansible_os_family == "Debian"

    - name: Replace Yandex mirror with official Ubuntu repositories
      copy:
        content: |
          deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0644'

- name: Update apt cache
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

- name: Configure Bastion Server
  hosts: bastion
  become: true
  tasks:
    - name: Install necessary packages
      apt:
        name: iptables
        state: present
      when: ansible_os_family == "Debian"

    - name: Open SSH port on Bastion
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        source: 0.0.0.0/0
        jump: ACCEPT
      become: true

    - name: Allow forwarding to web servers from Bastion
      ansible.builtin.iptables:
        chain: FORWARD
        protocol: tcp
        destination: 192.168.20.0/24
        jump: ACCEPT
      become: true

    - name: Forward Zabbix portal
      ansible.builtin.iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        destination_port: 8080
        jump: DNAT
        to_destination: 192.168.10.27:80
      become: true

    - name: Forward Kibana portal
      ansible.builtin.iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        destination_port: 8081
        jump: DNAT
        to_destination: 192.168.10.26:5601
      become: true

    - name: Forward Elasticsearch portal
      ansible.builtin.iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        destination_port: 8082
        jump: DNAT
        to_destination: 192.168.20.25:9200
      become: true

    - name: Forward Nginx web1
      ansible.builtin.iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        destination_port: 8083
        jump: DNAT
        to_destination: 192.168.20.5:80
      become: true

    - name: Forward Nginx web2
      ansible.builtin.iptables:
        chain: PREROUTING
        table: nat
        protocol: tcp
        destination_port: 8084
        jump: DNAT
        to_destination: 192.168.21.24:80
      become: true

- name: Configure Web Servers
  hosts:
    - fhmnqnglbq59e8sijb0e.auto.internal
    - epd8upobbm0d68il6pjl.auto.internal
  become: true
  vars_files:
    - /home/lukianchikovai/netology-diploma/ansible/vars.yml
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy index.html to web servers
      copy:
        src: /home/lukianchikovai/netology-diploma/ansible/index.nginx-ubuntu.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configure Nginx for static site
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

- name: Install and Configure Monitoring Tools
  hosts: all
  become: true
  vars_files:
    - /home/lukianchikovai/netology-diploma/ansible/vars.yml
  tasks:
    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix Agent
      template:
        src: /home/lukianchikovai/netology-diploma/ansible/templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted

- import_playbook: install_elasticsearch.yml

- name: Install Kibana
  hosts:
    - kibana.ru-central1.internal
  become: true
  vars_files:
    - /home/lukianchikovai/netology-diploma/ansible/vars.yml
  tasks:
    - name: Install Kibana
      apt:
        name: kibana
        state: present

    - name: Configure Kibana
      template:
        src: templates/kibana.yml.j2
        dest: /etc/kibana/kibana.yml
      notify:
        - restart kibana

    - name: Restart Kibana
      service:
        name: kibana
        state: restarted

  handlers:
    - name: restart kibana
      service:
        name: kibana
        state: restarted

- name: Install Filebeat
  hosts:
    - fhmnqnglbq59e8sijb0e.auto.internal
    - epd8upobbm0d68il6pjl.auto.internal
  become: true
  vars_files:
    - /home/lukianchikovai/netology-diploma/ansible/vars.yml
  tasks:
    - name: Install Filebeat
      apt:
        name: filebeat
        state: present

    - name: Configure Filebeat
      template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
      notify:
        - restart filebeat

    - name: Restart Filebeat
      service:
        name: filebeat
        state: restarted

  handlers:
    - name: restart filebeat
      service:
        name: filebeat
        state: restarted
